//
// Created by Stéphane on 25.10.23.
//

#ifndef EMUCHIP8_CONFIG_H
#define EMUCHIP8_CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip8 Emulator"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_PROGRAM_LOAD_ADRESS 0x200
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_WINDOWS_MULTIPLIER 10

#define CHIP8_TOTAL_DATA_REGISTERS 16
#define CHIP8_TOTAL_STACK_DEPTH 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_CHARACTER_SET_LOAD_ADRESS 0x00

#endif //EMUCHIP8_CONFIG_H
